builders:
  retrofit_commandable:
    import: "package:retrofit_commandable_generator/builder.dart"
    builder_factories:
    - retrofitCommandBuilder
    build_extensions: {".dart": [".comm.dart"]}
    auto_apply: root_package
    build_to: source
    runs_before: ["json_serializable"]