builders:
  command_runnable:
    import: "package:command_runnable_generator/builder.dart"
    builder_factories:
    - runnableBuilder
    build_extensions: {".dart": [".comm.dart"]}
    auto_apply: root_package
    build_to: source
    runs_before: ["json_serializable"]