name: retrofit_commandable
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: arxing <meiswind711108@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  source_gen: any
  retrofit_commandable:
    path: ../annotation

dev_dependencies:
  test: ^1.6.0
  build_runner: any
