name: retrofit_commandable_generator
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: arxing <meiswind711108@gmail.com>

environment:
  sdk: '>=2.5.2 <3.0.0'

dependencies:
  path: ^1.6.0
  source_gen: ^0.9.4+7
  retrofit_commandable:
    git:
      url: https://github.com/Arxing/dart-retrofit_commandable.git
      path: annotation

dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.6.7
