name: command_runnable_generator
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: arxing <meiswind711108@gmail.com>

environment:
  sdk: '>=2.5.2 <3.0.0'

dependencies:
  path: ^1.6.0
  source_gen: ^0.9.4+7
  command_runnable:
#    path: W:\dart\command_runnable\annotation
    git:
      url: https://github.com/Arxing/dart-retrofit_commandable.git
      path: annotation
  build: ^1.2.1
  dartpoet: ^1.0.6+3

dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.6.7
