name: command_runnable
description:
version: 1.0.0
homepage: https://github.com/Arxing/dart-command_runnable
author: arxing <meiswind711108@gmail.com>

environment:
  sdk: '>=2.5.2 <3.0.0'

dependencies:
  meta: ^1.1.8
